<?php

namespace App\Modules\BackEnd\Controllers;

use Illuminate\Http\Request;

use App\Models\Supports as THIS;

class SupportsController extends BackendController
{
    protected $timeStamp = 'created';
    protected $folder_upload = 'avatar_supports';
    //config controller, ez for copying and paste
    public function __construct(){
        parent::__construct(new THIS(),[
            [
                'name' => 'required',
                'position' => 'required',
                'email' => 'required|email',
                'phone' => 'required|numeric',
                'facebook' => 'required|url',
                'avatar_supports' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            ]
        ]);

    }

    public function index(Request $request){
        $order = 'created DESC, id DESC';
        $cond = [['status','>',0]];
        if($request->name != ''){
            $cond[] = ['name','LIKE','%'.$request->name.'%'];
        }
        if(!empty($request->time_from)){
            $timeStamp = \Lib::getTimestampFromVNDate($request->time_from);
            array_push($cond, ['created', '>=', $timeStamp]);
        }
        if(!empty($request->time_to)){
            $timeStamp = \Lib::getTimestampFromVNDate($request->time_to, true);
            array_push($cond, ['created', '<=', $timeStamp]);
        }
        if(!empty($cond)) {
            $data = THIS::where($cond)->orderByRaw($order)->paginate($this->recperpage);
        }else{
            $data = THIS::orderByRaw($order)->paginate($this->recperpage);
        }
        return $this->returnView('index', [
            'data' => $data,
            'search_data' => $request
        ]);
    }
    public function beforeSave(Request $request, $ignore_ext = [])
    {
        $this->uploadImage($request, $request->name, 'avatar_supports');
        parent::beforeSave($request); // TODO: Change the autogenerated stub
        $this->uploadImage($request, $request->name, 'avatar_supports');

    }
}
